#  docker-compose up -d
#  docker-compose down --remove-orphans

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: start-dev
    ports:
      - 8080:8080
    networks:
      - keycloak-mysql-network
    # working_dir: /app
    # volumes:
    #   - ./:/app
    environment:
      # TODO: replace with a config file.
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin # TODO: secret
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password # TODO: secret
    depends_on:
      - mysql-keycloak
  mysql-keycloak:
    image: mysql:8.0
    ports:
      - 3306:3306
    networks:
      - keycloak-mysql-network
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password # TODO: secret  

networks:
  keycloak-mysql-network:
